### PR TITLE
Add ase_read example

### PR DESCRIPTION
**Pull request by tyamaguchi17**
Signed-off-by: tyamaguchi <charmq@preferred.jp>

ase.io.readがinitial_chargeを持つxyz fileのreadに失敗するbugに対するwork around

### CODE REVIEW

**Review by corochann — APPROVED** [review]
LGTM, thank you.

**Comment by corochann** [comment]
Note that this bug arises even user does not set initial_charges explicitly.

When user repeated write & read with only charge property

 - xyz write atoms with calculated charge
 - xyz read --> the prev charge is set as initial_charge
 - xyz write --> atoms with initial_charge, and calculated charge
 - xyz read --> cannot read both initial_charge & charge. ERROR.

**Comment by tyamaguchi17** [comment]
>Note that this bug arises even user does not set initial_charges explicitly.
このパターンについても追加したので確認お願いします

**Review by corochann — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
